name: Test

on:
  pull_request:
    branches:
      - 'main'

jobs:
  test:
    name: Test app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: install d
        run: npm ci

      - name: lint
        run: npm run lint